name: Keep Alive Render
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Service
        run: |
          echo "Keep-alive active. Pinging service..."
          curl -s https://hng-14-be-stage-1.onrender.com/health
